### ISSUE TITLE
More carrying capacity

### ISSUE THREAD

**Issue by Opportunisticly** [Fallout-The-Wild-Wastelands/The-Wild-Wastelands#1]
### I feel like you should be able to upgrade your carrying capacity so here is my suggestion.

**_Backpacks:_**
There can be various backpacks you can find that are rare and have varying effect on your carrying capacity, like, a school bag for example will let you only carry a couple extra items, but items like a duffle bag for example will let you carry more, however, the more items you carry, the slower you get, and maybe it will affect AP as well.

**_Power armor:_**
Having power armor equipped will increase your carrying capacity without affecting AP or slowing you down, however, you won't be able to equip a backpack, it also won't be a lot, you can only carry a couple of extra items.

**_Mutants:_**
Mutants have the same stats with storage capacity like power armor, they cannot equip backpacks, and they aren't slowed down, and their AP isn't affected.

_**I'm not saying you do everything this suggestion says, just take bits and bobs from it, i'm just giving out ideas.**_

**Comment by Rythian2277** [comment]
I do want to add a system similar to this which reads your current armour and alters your carry weight (PA weight being negated when worn for example). I didn't think about Backpacks though and that is actually a very interesting route we can go down to give non-faction members additional inventory space.

If backpacks are added, they will most likely be added to the **Server** shops and will not be allowed to be traded in the player to player trading system.

**Comment by Opportunisticly** [comment]
> I do want to add a system similar to this which reads your current armour and alters your carry weight (PA weight being negated when worn for example). I didn't think about Backpacks though and that is actually a very interesting route we can go down to give non-faction members additional inventory space.
> 
> If backpacks are added, they will most likely be added to the **Server** shops and will not be allowed to be traded in the player to player trading system.

thanks for taking my backpack idea into consideration

**Comment by Rythian2277** [comment]
Implemented in rewrite. Inventory space now uses a weight based system so there is no physical cap on the amount of items, just the amount you can carry under a weight limit.
