### ISSUE TITLE
Weapon/Armor conditions & repairing

### ISSUE THREAD

**Issue by Opportunisticly** [Fallout-The-Wild-Wastelands/The-Wild-Wastelands#10]
### Mechanics:

**Weapons:**
When a weapon is constantly fired, it will degrade, if the weapon is something like a minigun or laser gun, it will degrade much much faster compared to a laser rifle, or even a varmint.

**Armor:**
If you are wearing armor while taking damage, the armors condition will degrade, lower end armors like leather armor degrade faster compared to something like power armor.

### Maintenance:

**Repairing:**
You can repair items via your pipboy, higher end items like power armor or miniguns will need more repair materials and scrap to repair.

**Repair materials:**
Scattered throughout the wasteland are things like duct tape or glue, which are a component needed to repair items, along with scrap of course. You can also buy repair kits from merchants or find them. Repair kits will repair a quarter of the condition while  duct tape and glue will repair half a quarter, scrap is just a requirement.

**Comment by Rythian2277** [comment]
I won't be adding this feature as it would add additional metadata (data which exists solely to give extra information) to save files which are already large enough.

As much as I like the idea it's physically impossible as the degredation bar has already been removed from the game in favour of a timer bar intended for use with events.

Sorry.

**Comment by Opportunisticly** [comment]
rip
