### ISSUE TITLE
Armor & Weapon mods

### ISSUE THREAD

**Issue by Opportunisticly** [Fallout-The-Wild-Wastelands/The-Wild-Wastelands#11]
### A mechanic in NV where you could add mods to your weapons via your pipboy, but with a twist, also including mods to armors, and disadvantages, you can only equip 1 mod and they can only be bought from merchants also for example an extended mag mod increases ammo capacity at the expense of reload speed.

**List of weapon mods:**
Laser sight.
Extended magazine.
Long barrel.
Short Barrel
Hairline trigger.
Improved receiver.
Improved handguard.
Improved sights.
Lightweight frame.

**List of armor mods:**
Reinforced plating.
Lightweight plating.
Storage pockets.
Improved fittings.

**Comment by Rythian2277** [comment]
Unfortunately, this has the same issue as #10 concerning stored data and interfaces, it may be possible down the line but I have no immediate plans to add this functionality.
